### ISSUE TITLE
URL special characters in DISKA_FILES_URL

### ISSUE THREAD

**Issue by digitalica** [ppeccin/WebMSX#10]
I'm trying to load 

http://webmsx.org/?MACHINE=MSX1E&DISKA_FILES_URL=http://www.msxcomputermagazine.nl/archief/listings/mcmd01.di1/blue%26pin&BASIC_RUN=blue%26pin

Note the url escaped & in the filename 'blue&pin'.

the basic_run works, but the file doesn't. The request the emulator makes to my server is:

54.147.43.152 - - [01/Feb/2017:10:27:25 +0100] "GET /listings/mcmd01.di1/blue HTTP/1.1" 404 508 "-" "-"

note filename is missing '&pin'. And the resulting 404 error.

looks like the emulator doesn't escape the filename. I think it should, although i could probably make it work by escaping twice ;-)

I would prefer not to change the weird (but historically correct) filenames of course.

**Comment by digitalica** [comment]
Ive been checking your code, found the console log:

Reading file from: http://www.msxcomputermagazine.nl/archief/listings/mcmd01.di1/blue&pin

(wont work, without escaping the &)

and realized as I'm giving you a URL, maybe i *should* escape twice. But that doesnt work eigther:

http://webmsx.org/?MACHINE=MSX1E&DISKA_FILES_URL=http://www.msxcomputermagazine.nl/archief/listings/mcmd01.di1/blue%2526pin&BASIC_RUN=blue%26pin

console log then shows correctly:
Reading file from: http://www.msxcomputermagazine.nl/archief/listings/mcmd01.di1/blue%26pin

looks like the the files command shows me 'BLUE%2~1'  then ;-)

hmmm....

**Comment by ppeccin** [comment]
I used your link, and when I run a "FILES" command, I see a file "BLUE%2~1"

So that is the name you should try to use in the BASIC_RUN command.

I realize that this is probably an issue in the way the automatic image
builder is treating the "&" character in the original filename. It is
seeing the "&" as in invalid character and is renaming the file to
something possible.

This probably can be improved, but for now, use the renamed file name, OR
if you really want to keep the original file name, for that specific case
you will have to create a disk image (.DSK) with you file to preserve the
name, then load the image. It will work.

**Comment by digitalica** [comment]
i tested wrapping problematic files in a zip. That works.
So I think wel´ll just create zips for every disk just without the autoexec. That way, naming issues will be solved and we can also run a specific program, not the autoexec.

thanks for your help
