### ISSUE TITLE
Bug: WebMSX looses ROM information

### ISSUE THREAD

**Issue by TFHFony** [ppeccin/WebMSX#19]
With certain ROMS, it can happen that you loose the inserted ROM when selecting another machine. For example, go to this page:

http://www.file-hunter.com/MSX/KingsValley2.html
Go to the Select Machine menu
Select MSX2+ European
And the ROM in slot 1 is gone

**Comment by ppeccin** [comment]
Its not "losing" the ROM since there is still something inserted on the slot, but somehow after the machine changed it now thinks that its an empty KonamiSCC cartridge.

Looking at your page, I found the problem. You´re forcing (via JS) a preset to be loaded:

WMSX.PRESETS = "SCC";

When you change the machine, it reloads the components of the presets chosen. So with this you are basically asking for 2 ROMS to be inserted on the same slot. The first launch the machine is configured as asked (KonamiSCC inserted on slot 1 as the preset defines), and THEN one game cartridge is loaded and inserted on the same slot (KingsValley2).

When you ask for the machine change it reloads the presets and then reinserts the KonamiSCC cart in slot 1.

Just remove that preset completely, You don't need to select the SCC preset when you are inserting a game that already has its own SCC.

Please use the SCC/SCC+ presets only when you want an empty SCC cartridge on the slot with no games, like for playing music or loading games on them with loaders, etc...

Paulo

**Comment by TFHFony** [comment]
Hi Paulo,

Indeed :) It seems I still had a few games where I was using the SCC preset
this way in the past, and forgot somehow to remove it. I have scanned all
my .html files and removed it from all of those who don't need it.

Thanks for the quick feedback!

Arnaud
