### ISSUE TITLE
Poor performance on Android and IOS

### ISSUE THREAD

**Issue by retrofan1979** [ppeccin/WebMSX#67]
Hi, first of all: I like your concept for an online MSX emulator! It works great on my Windows PC, but on my mobile devices with Android and IOS it doesn't run very smooth and even with interrupted audio playback.
Is there a way you can fix this, maybe optimizing it for these platforms?
Which webbrowser is preferred for WebMSX? Google Chrome?

**Comment by ppeccin** [comment]
Hi!
Thank you, it's nice you liked WebMSX.

The emulator runs perfectly on the Android and iOS devices I tested. But
it's kind of heavy, you will need a relatively "good" device, like iPhone6
or greater, Galaxy S7, and so.
On some Android devices, especially the cheaper ones, you may need to
increase the Audio Buffer, so the sound does not get interrupted. The
option is on the settings inside the emulator itself, and once set it will
be remembered on next sessions.

One other thing you can do to improve performance is to run the emulator in
"standalone" mode. Open the website and use your browser "Add to
homescreen" option. When you open it via the installed icon, it will run a
little better.

I recommend Chrome on Android, and also on iOS but it does not really
matter since all browserers must use the same Safari core on iOS.
Also please check if your browser has too many open tabs, or maybe your
device is running other heavy tasks in the background.

Please also check my other online emulator: https://javatari.org

Regards!
Paulo

**Comment by retrofan1979** [comment]
Hi, okay, thanks, I will try.
I now use Google Chrome Lite mode on Android. Then it works much better.
Keep up the great work!
Maybe you also can add more emulators like SNES and PSX? ;-) I will also try Javatari!

**Comment by ppeccin** [comment]
Well, WebMSX and Javatari are not ports of other emulators, they were
programmed from scratch and took several months/years of work to get to
that point!  ;-)
But.... Maybe in the future, who knows?  :-)

Paulo
